## Numpy

In [2]:
import numpy as np

In [8]:
#from list 
list=[1.5,2,3]
x=np.array(list)
x

array([1.5, 2. , 3. ])

In [9]:
x.shape #元组中的 3 表示 x 的第一个维度（长度）有 3 个元素。(3,) 中的逗号表示这是一个一维数组

(3,)

In [10]:
x.size #size等于数组所有维度大小的乘积

3

In [11]:
x.dtype #x.dtype 返回 NumPy 数组的元素数据类型。
#可以通过 dtype 属性了解数组中元素的数据类型，确保数据类型在运算中的准确性。
#dtype 是一个 NumPy 的数据类型对象（如 int64, float32, str 等）。

dtype('float64')

In [12]:
#create 20 arrays from list of lists
list2=[[1,2,3],[4,5,6,]]
b=np.array(list2)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [16]:
c=np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
c.shape

(3, 2)

In [19]:
#create 30 arrays (2,2,3)
list3=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
d=np.array(list3)
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
d.shape

(2, 2, 3)

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
#arange function, we pass in a start, a stap, and a step size
#return evenly spaced
np.arange(0,10,2) #将生成一个数组，从 0 开始，以步长为 2，直到小于 10 为止

array([0, 2, 4, 6, 8])

In [28]:
#linspace, returns a specofied number of evenly spaced value
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [32]:
d1arr=np.linspace(0,10,6)
d2arr=d1arr.reshape(2,3)
d1arr
d2arr

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

In [33]:
d1arr=np.linspace(0,10,12)
d3arr=d1arr.reshape(2,2,3)
print(d1arr)
print(d3arr)

[ 0.          0.90909091  1.81818182  2.72727273  3.63636364  4.54545455
  5.45454545  6.36363636  7.27272727  8.18181818  9.09090909 10.        ]
[[[ 0.          0.90909091  1.81818182]
  [ 2.72727273  3.63636364  4.54545455]]

 [[ 5.45454545  6.36363636  7.27272727]
  [ 8.18181818  9.09090909 10.        ]]]


### Indexing & slicing

In [45]:
arr_1D=np.array([10,20,30,40,50])
arr_1D[2]

30

In [35]:
#2D array of 3x3
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[1,1]

5

In [36]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[:,1]

array([2, 5, 8])

In [43]:
#3D array of 2x3x3
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
print(arr_3D)
print(arr_3D[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
6


In [44]:
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
print(arr_3D[1,1,0])
print(arr_3D[:,0,:])

13
[[ 1  2  3]
 [10 11 12]]


In [47]:
#fancy indexing
arr_1D=np.array([10,20,30,40,50])
arr_1D[[2,3]]

array([30, 40])

In [48]:
#2D array of 3x3
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
rows=[0,2]
cols=[1,2]
print(arr_2D[rows,:])
arr_2D[rows,cols]

[[1 2 3]
 [7 8 9]]


array([2, 9])

In [50]:
#3D array of 2x3x3
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
depth_ind=[0,1]
row_ind=[0,1]
col_ind=[1,2]
print(arr_3D[depth_ind,:,:])
arr_3D[depth_ind,row_ind,col_ind]
#return two elements based on the combination of corresponating indices

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([ 2, 15])

In [51]:
arr=np.array([10,20,30,40,50])
#create a boolean indexing  by applying a condition
cond=arr>30
arr[cond]

array([40, 50])

In [54]:
#select element greater than 20 and less than 50
cond=(arr>20)&(arr<50)
arr[cond]

array([30, 40])

In [56]:
#2D array of 3x3
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[arr_2D>5]

array([6, 7, 8, 9])

In [57]:
#3D array of 2x3x3
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
#print(arr_3D)
print(arr_3D[arr_3D>10])

[11 12 13 14 15 16 17 18]


### slicing

In [63]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
#slice from index 2 to 6 (exclusive)
print(arr[2:6])
#slice from start to 5 (exclusive)
print(arr[:5])
#slice from index 3(inclusive) to end 
print(arr[3:])
#slice with step 2 
print(arr[0:9:2])
#slice the last 3 elements
print(arr[-3:])

[2 3 4 5]
[0 1 2 3 4]
[3 4 5 6 7 8 9]
[0 2 4 6 8]
[7 8 9]


In [65]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
#slice the first two rows and first two colums
print(arr_2D[:2,:2])
#slice the first two rows and first two colums
print(arr_2D[-2:,-2:])

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [66]:
#3D array of 2x3x3
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
#slice last depth, row 1 to 2, and last column
print(arr_3D[-1:,1:3,-1:])
#slice first depth, all row, and column from index 1
print(arr_3D[0,:,1:])

[[[15]
  [18]]]
[[2 3]
 [5 6]
 [8 9]]


### Array manipulation

In [71]:
#1D array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#concatenate along the first axis
con_1D=np.concatenate((arr1,arr2))
print(con_1D)

#2D array
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6],[7,8]])
#concatenate along the column (first axis)
con_2D=np.concatenate((arr3,arr4),axis=1)
print(con_2D)
#concatenate along the column (axis 0)
con_2D_2=np.concatenate((arr3,arr4),axis=0)
print(con_2D_2)



[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [79]:
#1D array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#concatenate along the first axis
con_1D=np.concatenate((arr1,arr2))
print(con_1D)

#2D array
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6],[7,8]])
#concatenate along the column (first axis)
con_2D=np.concatenate((arr3,arr4),axis=1)
print(con_2D)
#concatenate along the column (axis 0)
con_2D_2=np.concatenate((arr3,arr4),axis=0)
print(con_2D_2)

#3D array 
arr1=np.arange(18).reshape(2,3,3)
arr2=np.arange(18,36).reshape(2,3,3)
#concatenate along axis 0(depth)
c_0=np.concatenate((arr1,arr2),axis=0)
print(c_0.shape)
#concatenate along axis 1(drow)
c_1=np.concatenate((arr1,arr2),axis=1)
#concatenate along axis 2(drow)
c_2=np.concatenate((arr1,arr2),axis=2)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 3, 3)


In [81]:
#np.split split your array into multiple sub-arrays 
arr=np.arange(10)
print(arr)
#split 2 equal parts
split_arr=np.split(arr,2)
print(split_arr)
#split based on indince
split_ind=np.split(arr,[3,7])
print(split_ind)
for part in split_ind:
    print(part)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]
[0 1 2]
[3 4 5 6]
[7 8 9]


In [82]:
#2D array 
arr=np.arange(24).reshape(6,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [90]:
#split the array at specific indices along the rows
split_arr=np.split(arr,[2,4],axis=0)
print(split_arr)

split_arr1=np.split(arr,[1,2],axis=1)
print(split_arr1)

split_arr2=np.split(arr1,[1,2],axis=1)
print(split_arr2)

[array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]]), array([], shape=(0, 3, 2), dtype=int32), array([], shape=(0, 3, 2), dtype=int32)]
[array([[[0, 1]],

       [[6, 7]]]), array([[[2, 3]],

       [[8, 9]]]), array([[[ 4,  5]],

       [[10, 11]]])]
[array([[[ 0,  1,  2]],

       [[ 9, 10, 11]]]), array([[[ 3,  4,  5]],

       [[12, 13, 14]]]), array([[[ 6,  7,  8]],

       [[15, 16, 17]]])]


In [93]:
#3D
arr=np.arange(12).reshape(2,3,2)

split0=np.split(arr,2,axis=0)
print(split0)

split1=np.split(arr,3,axis=1)
print(split1)

split2=np.split(arr,2,axis=2)
print(split2)

[array([[[0, 1],
        [2, 3],
        [4, 5]]]), array([[[ 6,  7],
        [ 8,  9],
        [10, 11]]])]
[array([[[0, 1]],

       [[6, 7]]]), array([[[2, 3]],

       [[8, 9]]]), array([[[ 4,  5]],

       [[10, 11]]])]
[array([[[ 0],
        [ 2],
        [ 4]],

       [[ 6],
        [ 8],
        [10]]]), array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]]])]


In [86]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])