In [2]:
import numpy as np

In [11]:
#creat 
arr=np.arange(24).reshape(4,2,3)#四个切片 每个切片两行，每行三个元素
print(arr)
#split along the depth (axis=0)
split_arr_depth=np.split(arr,[2,3],axis=0)
print(split_arr_depth)

#split
split_arr_col=np.split(arr,[1],axis=2)
print(split_arr_col)



[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
[array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]]), array([[[12, 13, 14],
        [15, 16, 17]]]), array([[[18, 19, 20],
        [21, 22, 23]]])]
[array([[[ 0],
        [ 3]],

       [[ 6],
        [ 9]],

       [[12],
        [15]],

       [[18],
        [21]]]), array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23]]])]


In [13]:
for part in split_arr_col:
    print(part.shape)

(4, 2, 1)
(4, 2, 2)


In [17]:
#create a 2D array(4x4)
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

arr_v=np.vsplit(arr2,2)
print(arr_v)

arr_sv=np.split(arr2,[2],axis=0)
print(arr_sv)

arr_h=np.hsplit(arr2,2)
print(arr_h)

arr_sh=np.split(arr2,[2],axis=1)
print(arr_sh)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


### Ufunc & arithmetic

In [27]:
#Define two arrays
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

add_r=a+b
print(add_r)

sub_r=a-b
print(sub_r)

mult_r=a*b
print(mult_r)

div_r=a/b
print(div_r)

pow_r=a**b
print(pow_r)

less_r=a<4
print(less_r)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ True  True  True False]


In [24]:
#unary ufunc 
arr=np.array([1,2,3,4,5])

np.mean(arr)
np.median(arr)
np.std(arr)
np.sum(arr)

15

In [28]:
#binary ufunc
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

add_r=np.add(a,b)
print(add_r)

sub_r=np.subtract(a,b)
print(sub_r)

mult_r=np.multiply(a,b)
print(mult_r)

div_r=np.divide(a,b)
print(div_r)

pow_r=np.power(a,b)
print(pow_r)

less_r=np.less(a,b)
print(less_r)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ True  True  True  True]


In [36]:
import time 
#create a large array 
x=np.random.rand(100000000)

start=time.time()
result_operator=x<5
print("Time using x<5:",time.time()-start)

start=time.time()
result_operator=np.less(x,5)
print("Time using np.less:",time.time()-start)

Time using x<5: 0.04686474800109863
Time using np.less: 0.062488555908203125


In [38]:
##Matrix
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

mat_add=A+B

mat_mul=A*B

mat_tran=A.T

print(mat_add)
print(mat_mul)
print(mat_tran)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]


### View & Coppy

In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

#slice the first two rows
view_arr=arr[0:2,:].copy() 
print(view_arr)

#modify an element of view_arr
view_arr[0,0]=99
print("modified array with copy:")
print(view_arr)

print("\noringinal array:")
print(arr)

[[1 2 3]
 [4 5 6]]
modified array with copy:
[[99  2  3]
 [ 4  5  6]]

oringinal array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
arr=np.array([10,20,30,40])

#fancy index
fancy_view=arr[[1,3]].copy()

#modify fancy_view
fancy_view[0]=99
print("modified array :",fancy_view)
print("oringinal array :",arr)

modified array : [99 40]
oringinal array : [10 20 30 40]


In [55]:
#build a function to normalize a specifix column in 20 array 
def norm_col_2D(arr,col_index):
    norm_arr = arr.copy()

    col_arr=norm_arr[:,col_index]

    mean=np.mean(col_arr)
    std_dev=np.std(col_arr)

    norm_arr[:,col_index]=(col_arr-mean)/std_dev

    return norm_arr,arr
    

In [57]:
ori_arr=np.array([[60,70,80],
                [90,100,110],
                  [120,130,140],
                 [150,160,170],
                 [180,190,200]])
modified_arr,original_arr=norm_col_2D(ori_arr,1)
print("output:",modified_arr)
print("input:",original_arr)

output: [[ 60  -1  80]
 [ 90   0 110]
 [120   0 140]
 [150   0 170]
 [180   1 200]]
input: [[ 60  70  80]
 [ 90 100 110]
 [120 130 140]
 [150 160 170]
 [180 190 200]]


### Pandas

In [58]:
import pandas as pd

#### Bi

In [59]:
#create from list
data=[10,20,30,40,50]
s1=pd.Series(data)
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [62]:
custom_index=['a','b','c','d','e']
s1_customind=pd.Series(data,index=['a','b','c','d','e'])
print(s1_customind)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [69]:
new_series=s_numpy.drop('C')
print(new_series)

A    10
B    20
D    40
E    50
dtype: int32


In [61]:
#create from Numpy array 
narr=np.array([10,20,30,40,50])

s_numpy=pd.Series(narr,index=['A','B','C','D','E'])

print(s_numpy)

A    10
B    20
C    30
D    40
E    50
dtype: int32


In [63]:
#create from dictionary
dict={'a':10,'b':20,'c':30,'d':40,'e':50}
s_dict=pd.Series(dict)
print(s_dict)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [64]:
#from list of lists 
data_list=[[1,5,6],[2,6,10],[3,7,11]]
df_from_list=pd.DataFrame(data_list,columns=['A','B','C'],index=['r1','r2','r3'])
print(df_from_list)

    A  B   C
r1  1  5   6
r2  2  6  10
r3  3  7  11


In [65]:
#from 2D Numpy
data_numpy=np.array([[1,5,6],[2,6,10],[3,7,11]])
df_from_numpy=pd.DataFrame(data_numpy,columns=['A','B','C'],index=['r1','r2','r3'])
print(df_from_numpy)

    A  B   C
r1  1  5   6
r2  2  6  10
r3  3  7  11


In [67]:
#from dictionary
data_dict={
    'A':[1,2,3],
    'B':[5,6,7],
    'C':[6,10,11]
}
df=pd.DataFrame(data_dict,index=['r1','r2','r3'])
print(df)

    A  B   C
r1  1  5   6
r2  2  6  10
r3  3  7  11


In [68]:
df2=pd.DataFrame(
    {
        "Name":["Ahmad","Ali","Ain"],
        "Age":[30,25,23], 
         "Sex":["male","male","female"]
    }
)
print(df2)

    Name  Age     Sex
0  Ahmad   30    male
1    Ali   25    male
2    Ain   23  female


In [71]:
df2.drop("Age",axis=1)

Name     Sex
0  Ahmad    male
1    Ali    male
2    Ain  female

In [72]:
df2.drop(0)

Name  Age     Sex
1  Ali   25    male
2  Ain   23  female

In [73]:
df2.drop([0,2])

Name  Age   Sex
1  Ali   25  male

In [74]:
df2.drop(['Name','Age'],axis=1)

Sex
0    male
1    male
2  female

In [75]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Sex     3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [76]:
s_dict['b']

20

In [77]:
s_dict[1]

C:\Users\Dell\AppData\Local\Temp\ipykernel_14496\2883873927.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s_dict[1]


20

In [78]:
s_dict.iloc[1]

20

In [79]:
s_dict[[1,2,3]]

C:\Users\Dell\AppData\Local\Temp\ipykernel_14496\1216125954.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s_dict[[1,2,3]]


b    20
c    30
d    40
dtype: int64

In [82]:
s_dict[s_dict>20]

c    30
d    40
e    50
dtype: int64

In [93]:
#from dictionary
data_dict={
    'A':[1,2,3],
    'B':[5,6,7],
    'C':[6,10,11]
}
df=pd.DataFrame(data_dict,index=['r1','r2','r3'])
print(df)

    A  B   C
r1  1  5   6
r2  2  6  10
r3  3  7  11


In [84]:
df[['A','B']]

A  B
r1  1  5
r2  2  6
r3  3  7

In [85]:
df.loc['r1']

A    1
B    5
C    6
Name: r1, dtype: int64

In [89]:
df.iloc[-1,-1:]

C    11
Name: r3, dtype: int64

In [92]:
df.iloc[-1,-1:2]

Series([], Name: r3, dtype: int64)

In [94]:
df.iloc[-1,-1:]

C    11
Name: r3, dtype: int64

In [95]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([10,20,30,40])

add_r=s1+s2
print(add_r)

0    11
1    22
2    33
3    44
dtype: int64


In [96]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[10,20],'B':[30,40]})
add_r=df1+df2
print(add_r)

    A   B
0  11  33
1  22  44


In [97]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]},index=['r1','r2'])
df2=pd.DataFrame({'A':[10,20],'B':[30,40]},index=['r2','r3'])
add_r=df1+df2
print(add_r)

       A     B
r1   NaN   NaN
r2  12.0  34.0
r3   NaN   NaN


In [100]:
df1=pd.DataFrame({'A':[1,2]})
s=pd.Series([1,2])

mult_r=s*df
print(mult_r)

     A   B   C   0   1
r1 NaN NaN NaN NaN NaN
r2 NaN NaN NaN NaN NaN
r3 NaN NaN NaN NaN NaN


In [101]:
df

A  B   C
r1  1  5   6
r2  2  6  10
r3  3  7  11

In [102]:
df1=pd.DataFrame({'A':[1,2]})
s=pd.Series([1,2])

mult_r=4*df
print(mult_r)

     A   B   C
r1   4  20  24
r2   8  24  40
r3  12  28  44


In [103]:
#create dataframe with diplicate columns
data={'A':[1,2,3],'B':[4,5,6],'A':[7,8,9]}
df=pd.DataFrame(data)
print(df)

   A  B
0  7  4
1  8  5
2  9  6


In [121]:
#create from Numpy
data_array=np.array([[1,5,9],[2,6,10],[3,7,11],[4,8,12]])
df=pd.DataFrame(data_array,columns=['A','B','A'],index=['r1','r1','r2','r3'])
print(df)
#print(df['A'])
#print(df.loc['r1']*2)

#df['A_sum']=df['A']+df['B']
print(df)

    A  B   A
r1  1  5   9
r1  2  6  10
r2  3  7  11
r3  4  8  12
    A  B   A
r1  1  5   9
r1  2  6  10
r2  3  7  11
r3  4  8  12


In [122]:
df.index.duplicated()

array([False,  True, False, False])

In [123]:
df.columns.duplicated()

array([False, False,  True])

In [124]:
df[~df.index.duplicated()]

A  B   A
r1  1  5   9
r2  3  7  11
r3  4  8  12

In [128]:
df.T[~df.T.index.duplicated()].T

A  B
r1  1  5
r1  2  6
r2  3  7
r3  4  8

In [129]:
df.T

r1  r1  r2  r3
A   1   2   3   4
B   5   6   7   8
A   9  10  11  12

In [130]:
df.drop_duplicates()

A  B   A
r1  1  5   9
r1  2  6  10
r2  3  7  11
r3  4  8  12

In [131]:
df.describe()

A         B          A
count  4.000000  4.000000   4.000000
mean   2.500000  6.500000  10.500000
std    1.290994  1.290994   1.290994
min    1.000000  5.000000   9.000000
25%    1.750000  5.750000   9.750000
50%    2.500000  6.500000  10.500000
75%    3.250000  7.250000  11.250000
max    4.000000  8.000000  12.000000

In [132]:
df.mean()

A     2.5
B     6.5
A    10.5
dtype: float64

In [133]:
df.median()

A     2.5
B     6.5
A    10.5
dtype: float64

In [134]:
df.count()

A    4
B    4
A    4
dtype: int64

In [136]:
df['B'].nunique()

4

In [151]:
data=pd.Series([10,20,30,40,50])
data.isin([20,40])

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [137]:
data_array=np.array([[1,5,9],[2,6,10],[3,7,11],[4,8,12]])
df=pd.DataFrame(data_array,columns=['A','B','A'],index=['r1','r1','r2','r3'])
df['B'].isin([5])

r1     True
r1    False
r2    False
r3    False
Name: B, dtype: bool

In [141]:
#aplly ufunction to dataframe
data=pd.Series([10,20,30,40,50])
np.sum(data)

150

In [149]:
#apply ufunction to dataframe
data={'A':[1,2,3],'B':[3,4,5]}
df=pd.DataFrame(data)

print(df)

   A  B
0  1  3
1  2  4
2  3  5


In [150]:
df.apply(np.sum,axis=1)

0    4
1    6
2    8
dtype: int64

In [152]:
np.square(df)

A   B
0  1   9
1  4  16
2  9  25

In [153]:
df+2

A  B
0  3  5
1  4  6
2  5  7

In [156]:
df.map(lambda x:x**3)

A    B
0   1   27
1   8   64
2  27  125

In [160]:
def pow3(x):
    return x**3

df.map(pow3)

A    B
0   1   27
1   8   64
2  27  125

### Pivot Table 

In [166]:
data={
    'City':['Bangi','Klang','Bangi','Klang','Bangi'],
    'Product':['a','b','b','a','a'],
    'Sales':[2000,1500,3000,3500,1000]
}
df=pd.DataFrame(data)
df

City Product  Sales
0  Bangi       a   2000
1  Klang       b   1500
2  Bangi       b   3000
3  Klang       a   3500
4  Bangi       a   1000

In [167]:
#created pivot_table(df,values='Sales',index='City',Columns='Product','Sales')
pd.pivot_table(df,values='Sales',index='City',columns='Product',aggfunc='sum')

Product     a     b
City               
Bangi    3000  3000
Klang    3500  1500

In [168]:
pd.pivot_table(df,values='Sales',index='City',columns='Product',aggfunc='mean')

Product       a       b
City                   
Bangi    1500.0  3000.0
Klang    3500.0  1500.0

In [169]:
pd.crosstab(df['City'],df['Product'])

Product  a  b
City         
Bangi    2  1
Klang    1  1

### View & Copy

In [173]:
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
view=df['A'].copy()
view[0]=100
print("original dataframe:")
print(df)
print("\nmodified dataframe:")
print(view)

original dataframe:
   A  B
0  1  4
1  2  5
2  3  6

modified dataframe:
0    100
1      2
2      3
Name: A, dtype: int64


In [178]:
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})

subset=df[df['A']>2].copy()
subset

A  B
2  3  6

In [179]:
subset['B']=100

In [181]:
subset

A    B
2  3  100